Feature: Login functionality of orange # features/login.feature:1

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.1   # features/login.feature:10
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 0 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.2   # features/login.feature:11
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 1 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.3   # features/login.feature:12
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 2 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.4   # features/login.feature:13
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 3 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.5   # features/login.feature:14
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 4 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.6   # features/login.feature:15
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 5 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.7   # features/login.feature:16
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 6 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.8   # features/login.feature:17
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 7 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.9   # features/login.feature:18
    Given the login page is opened                                        # features/steps/login_steps.py:16
    When I enter the credentials from row 8 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                              # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.10   # features/login.feature:19
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 9 from excel                     # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.11   # features/login.feature:20
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 10 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.12   # features/login.feature:21
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 11 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.13   # features/login.feature:22
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 12 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.14   # features/login.feature:23
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 13 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.15   # features/login.feature:24
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 14 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.16   # features/login.feature:25
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 15 from excel                    # features/steps/login_steps.py:25
    Then I take a screenshot                                               # features/steps/login_steps.py:65

  Scenario Outline: Valid and invalid login attempts from Excel -- @1.17   # features/login.feature:26
    Given the login page is opened                                         # features/steps/login_steps.py:16
    When I enter the credentials from row 16 from excel                    # features/steps/login_steps.py:25
      Traceback (most recent call last):
        File "D:\Orange Test project\Orange\venv\Lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "D:\Orange Test project\Orange\venv\Lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 28, in step_enter_credentials_from_excel
          row = context.data[row_number]
                ~~~~~~~~~~~~^^^^^^^^^^^^
      IndexError: list index out of range

    Then I take a screenshot                                               # None

